# Generated by Django 3.2 on 2021-04-19 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 7, 34, 51, 44254, tzinfo=utc)),
        ),
    ]
