# Generated by Django 3.2 on 2021-04-19 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_post_date_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 9, 20, 19, 259280, tzinfo=utc)),
        ),
    ]
