# Generated by Django 3.2 on 2021-06-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_post_date_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
